config/routes.rb
InventorySystem::Application.routes.draw do
  resources :inventories

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base

  validates_presence_of :title
  validates_presence_of :description
  validates_numericality_of :quantity

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      redirect_to @inventory, notice: 'Inventory was successfully created.'
    else
      puts 'There was an error!'
      render :new
    end
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def index
    @inventories = Inventory.all
  end



  private

    def inventory_params
      params.require(:inventory).permit(:title, :description, :quantity)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventories/index.html.erb
<h1>Inventory List</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.title %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= form_for @inventory do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prevented this inventory from being saved:</h2>

      <ul>
        <% @inventory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div id="description">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div id="quantity">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div id="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<td><strong>Title: </strong><%= @inventory.title %></td><br>
<td><strong>Description: </strong><%= @inventory.description %></td><br>
<td><strong>Quantity: </strong><%= @inventory.quantity %></td><br>

<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventorySystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>